### ISSUE TITLE
cant get it to work.

### ISSUE THREAD

**Issue by samabergh** [Hellslicer/fivem-radio#1]

**Comment by samabergh** [comment]
hi i cant figure out how to get this to work. can some one help me a bit,..
I have written this in the lua .. supersede_radio "[RADIO_03_HIPHOP_NEW]" { url = "[http://www.nrj.no/player/?gclid=Cj0KCQjwtZzWBRD2ARIsAIPenY3raFru_SHLjmV5TaOP5TonwOk4bpAvBso-s7opzQdeUR-Ch6bP6ywaAoKoEALw_wcB]", volume = 0.5, name = "[nrj_no]" }
supersede_radio "[RADIO_04_PUNK]" { url = "[https://www.internet-radio.com/station/hardstylemusic/]", volume = 0.5, name = "[HARDSTYLE_MUSIC_Hardstyle]" }
supersede_radio "[RADIO_05_TALK_01]" { url = "[https://www.internet-radio.com/station/edmpulse/]", volume = 0.5, name = "[PulseEDM_Dance_Music_Radio]" }
supersede_radio "[RADIO_08_MEXICAN]" { url = "[https://www.internet-radio.com/station/classicbigrockhd/]", volume = 0.5, name = "[Classic_Rock_HD_Plus]" }

I hope you can help med to get this thing to work.

**Comment by Hellslicer** [comment]
Hi, you must:
* Remove the brackets
* Fix URL (URL should point to a stream instead of a web page)
* Not use MPEG, MP3 or AAC streams as it is currently not supported by CEF

Here's what it should look like:
```lua
supersede_radio "RADIO_03_HIPHOP_NEW" { url = "http://stream.p4.no/nrj_mp3_mq?Nettplayer_NRJ.no", volume = 0.5, name = "nrj_no" }
supersede_radio "RADIO_04_PUNK" { url = "http://uk5.internet-radio.com:8270/;stream", volume = 0.5, name = "HARDSTYLE_MUSIC_Hardstyle" }
supersede_radio "RADIO_05_TALK_01" { url = "http://pulseedm.cdnstream1.com:8124/1373_128", volume = 0.5, name = "PulseEDM_Dance_Music_Radio" }
supersede_radio "RADIO_08_MEXICAN" { url = "http://uk5.internet-radio.com:8251/;stream", volume = 0.5, name = "Classic_Rock_HD_Plus" }
```
