### ISSUE TITLE
Load, but dont works!

### ISSUE THREAD

**Issue by Nockerman** [Hellslicer/fivem-radio#12]
Hi, i found this scrpit a few days ago... I think it can be great but i cant set up correctly...

The script loads fine.

>Started resource fivem-radio

No errors in load... but when im in the game the script seems to do nothing...

in F8 says:

>script:fivem-radio:nui Uncaught (in promise) TypeError: Failed to fetch (@fivem-radio/index.html:0)

Thanks! :D

**Comment by NokaAngel** [comment]
Hey @Nockerman, that's been showing always, and I am trying to work on a fix to support CFX's nui issue's, to avoid this issue in the future, but the radio should still work normally and if not please do let me know.

**Comment by z0mbi0Xx** [comment]
Hello, I have the same issue that @Nockerman but the radio doesn't work.

**Comment by alexhorner** [comment]
Hey, also able to reproduce this issue, even with a fresh download of the script. Any information on this please?

**Comment by NokaAngel** [comment]
> Hey, also able to reproduce this issue, even with a fresh download of the script. Any information on this please?

Sorry for the late response, that's been a normal error. If you don't hear music then the stream URL type was set incorrectly, otherwise I've had no issues.

**Comment by alexhorner** [comment]
> 
> 
> > Hey, also able to reproduce this issue, even with a fresh download of the script. Any information on this please?
> 
> Sorry for the late response, that's been a normal error. If you don't hear music then the stream URL type was set incorrectly, otherwise I've had no issues.

Hi,

This was with a previously working installation across multiple separately-operated servers. It appeared to have been the result of an update to FiveM.

Unfortunately, we have since moved to another radio plugin for we needed this one resolved quickly, however thank you for your reply.

**Comment by NokaAngel** [comment]
> This was with a previously working installation across multiple separately-operated servers. It appeared to have been the result of an update to FiveM.
> 
> Unfortunately, we have since moved to another radio plugin for we needed this one resolved quickly, however thank you for your reply.

Understandable, have a good day/night wherever you are.

**Comment by Hellslicer** [comment]
I updated the resource to FXv2, it now fully works on latest FiveM builds for both HTTP and HTTPS radio streams.
