### ISSUE TITLE
2545 mpsecurity Radio Stations

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [Hellslicer/fivem-radio#14]
RADIO_01_CLASS_ROCK             // Los Santos Rock Radio

RADIO_02_POP                 // Non-Stop-Pop FM

RADIO_03_HIPHOP_NEW            // Radio Los Santos

RADIO_04_PUNK                  // Channel X

RADIO_05_TALK_01                 // West Coast Talk Radio

RADIO_06_COUNTRY                // Rebel Radio

RADIO_07_DANCE_01                // Soulwax FM

RADIO_08_MEXICAN                // East Los FM

RADIO_09_HIPHOP_OLD              // West Coast Classics

RADIO_11_TALK_02                 // Blaine County Radio

RADIO_12_REGGAE                 // Blue Ark

RADIO_13_JAZZ                    // Worldwide FM

RADIO_14_DANCE_02                // FlyLo FM

RADIO_15_MOTOWN                  // The Lowdown 91.1

RADIO_16_SILVERLAKE             // Radio Mirror Park

RADIO_17_FUNK                    // Space 103.2

RADIO_18_90S_ROCK               // Vinewood Boulevard Radio

RADIO_19_USER                    // User Music FM

RADIO_20_THELAB                  // The Lab

RADIO_21_DLC_XM17                // Blonded Los Santos 97.8 FM

RADIO_27_DLC_PRHEI4              // Still Slipping Los Santos

RADIO_34_DLC_HEI4_KULT           // Kult FM

RADIO_35_DLC_HEI4_MLR            // The Music Locker

RADIO_36_AUDIOPLAYER            // Media Player

RADIO_37_MOTOMAMI               // MOTOMAMI Los Santos

**Comment by Hellslicer** [comment]
Added in https://github.com/Hellslicer/fivem-radio/commit/c7722f17d4c0283cbe29d85fb78e70823dc5e798, thanks
