### ISSUE TITLE
Nothing happends after adding the script

### ISSUE THREAD

**Issue by robertpopa96** [Hellslicer/fivem-radio#4]
Hello Hellslicer and anyone else,

My name is Robert and i found your script a few days ago. I was very enthusiastic about it, but it didn't work on my server. It is an esx server and i have another 300 scripts on it, i just added it in the resources folder and started it from server.cfg. The resource was loaded but nothing happend. Can u help me with this, any tipps you have?

Thank you very much man, i appreciate your work.

**Comment by mickeygeecom** [comment]
300 scripts? holy fuck.

**Comment by Hellslicer** [comment]
Please use the appropriate forum thread for support or general questions
