### ISSUE TITLE
How do i change the volume (except in the __resource.lua) because it says player configurable

### ISSUE THREAD

**Issue by TakuyaSan420** [Hellslicer/fivem-radio#5]
Hello, 
How can i change the volume ingame? Because it says player configurable and i only saw a config in the __resource.lua which is not player configurable.

**Comment by mickeygeecom** [comment]
It follows your GTA option settings under Audio -> Music Volume

Though see my bug I've just reported: https://github.com/Hellslicer/fivem-radio/issues/6

**Comment by TakuyaSan420** [comment]
okey thanks. But i have another question. Is it possible to change the "now playing" in the game? The radios would be even better if the now playing would work. But Thanks for the script!

**Comment by Hellslicer** [comment]
Please use the appropriate forum thread for support or general questions
