### ISSUE TITLE
Max volume when you have muted music volume

### ISSUE THREAD

**Issue by mickeygeecom** [Hellslicer/fivem-radio#6]
Lovely resource, and have used it for a long time, though:

The volume is blasting out at max, if you have completely turned down volume in your GTA options.
Could this be fixed?

**Comment by Hellslicer** [comment]
Thanks. It should be fixed with https://github.com/Hellslicer/fivem-radio/commit/5985daf0060e88ede8c2322ce674a0babb2be20f
