### ISSUE TITLE
Failed load resource

### ISSUE THREAD

**Issue by DopePisa** [Hellslicer/fivem-radio#8]
"Couldn't load resource fivem-radio-master. :("
This is an error when i try to enter into my fivem server, i started  "fivem-radio-master" into server.cfg

**Comment by ThePinkPanda** [comment]
When I look at my server logs it says:

```Found new resource radio in D:/GTAServer/resources/radio```

So I would guess you should add the following instead of "fivem-radio-master":
```start radio```
